# Generated by Django 4.2.5 on 2023-09-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cs50notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecturenote",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
